In [1]:
import numpy as np

x = np.matrix([[1,2,6],[5,10,0],[0,10,10]])
A = np.matrix([0,2,1])
y = x * A.transpose()

print("A = ")
print(A)
print()

print("x = ")
print(x)
print()

print("y = ")
print(y)
print()

reg_A = np.linalg.inv(x.transpose()*x)*x.transpose()*y
print(reg_A)


A = 
[[0 2 1]]

x = 
[[ 1  2  6]
 [ 5 10  0]
 [ 0 10 10]]

y = 
[[10]
 [20]
 [30]]

[[1.77635684e-15]
 [2.00000000e+00]
 [1.00000000e+00]]
